import React from 'react';
import { render } from 'react-dom';
import ERD from './components/ERD';

/* eslint-disable import/prefer-default-export */

/**
 * Takes schema information generated by the Rails engine
 * and renders an ERD in the provided DOM element
 */
export const mountERD = (schema: any, element: Element) => {
  render(<ERD schema={schema} />, element);
};
